import { registerRootComponent } from 'expo';
import { Asset } from 'expo-asset';
import { File, Paths } from 'expo-file-system';
import { hideAsync } from 'expo-splash-screen';
import type { VideoPlayer } from 'expo-video';
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { AppState, Linking, Text, View } from 'react-native';
import { createEmptyReaderData } from '@/domain/reader/readerData';
import { TopicAudioSessionProvider, useTopicAudioControl } from '@/features/topic/media/TopicAudioSession';
import { diagnosticBuildContext } from '@/platform/diagnostics/nativeDiagnosticJournal';
import type { ForumMediaRequestContext } from '@/platform/media/mediaRequestContext';
import { MediaPlaybackSession, MediaPlaybackSessionContext } from '@/platform/media/mediaPlaybackSession';
import { applyNetworkProxy } from '@/platform/network/networkProxy';
import { getReadNetworkRuntimeSnapshot } from '@/platform/network/readNetworkRuntime';
import { ForumContentAudio } from '@/ui/content/ForumContentAudio';
import { ForumContentVideo } from '@/ui/content/ForumContentVideo';
import { createTheme } from '@/ui/theme/tokens';
import { waitForMediaProofChange } from './wait-for-change';

// Generated by ./generate-assets.mjs from lavfi patterns; no recordings or remote media.
const assets = [
  require('../../.codex-tmp/media-pressure-assets/video.mp4'),
  require('../../.codex-tmp/media-pressure-assets/audio-0.wav'),
  require('../../.codex-tmp/media-pressure-assets/audio-1.wav')
];
const manifest = require('../../.codex-tmp/media-pressure-assets/manifest.json') as {
  generator: string;
  files: { name: string; bytes: number; sha256: string }[];
};
void globalThis.Response;
globalThis.fetch = async () => {
  throw new Error('Network is unavailable in the local media proof');
};

const theme = createTheme(createEmptyReaderData().settings);
const context: ForumMediaRequestContext = { contentSource: null, sessionIdentity: 'local-media-pressure:0' };
type Control = ReturnType<typeof useTopicAudioControl>;
type Record = {
  player: VideoPlayer;
  kind: 'audio' | 'video';
  serial: number;
  timeEvents: number;
  seeks: number;
  fullscreen: boolean;
  fullscreenActive: boolean;
  detachedAt: number | null;
  fullscreenExitedAt: number | null;
  fullscreenExitPosition: number | null;
  fullscreenExitPlaying: boolean | null;
};
type Scenario = { token: string; rounds: number; minSeconds: number; externalEvery: number };

function check(value: unknown, message: string): asserts value {
  if (!value) throw new Error(message);
}
const delay = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

function observations() {
  const live = new Map<VideoPlayer, Record>();
  const controls = new Map<string, Control>();
  const errors: string[] = [];
  const changes = new Set<() => void>();
  const changed = () => {
    for (const listener of changes) listener();
  };
  const trace: { at: number; kind: string; event: string; value?: unknown }[] = [];
  const note = (kind: string, event: string, value?: unknown) => {
    trace.push({ at: performance.now(), kind, event, value });
    if (trace.length > 64) trace.shift();
    changed();
  };
  const counts = {
    created: 0,
    released: 0,
    peakPlayers: 0,
    observerSubscriptions: 0,
    fullscreenEntries: 0,
    fullscreenExits: 0,
    backgroundEntries: 0,
    foregroundReturns: 0
  };
  return {
    live,
    controls,
    errors,
    counts,
    trace,
    changes,
    changed,
    inlineVideoMounted: false,
    gates: { playbackActive: false, allowFullscreen: false, audioActive: true, audioPaused: true },
    note,
    recordVideoCommit(mounted: boolean) {
      this.inlineVideoMounted = mounted;
      note('route', 'video-commit', mounted);
    },
    recordGate(foreground: boolean) {
      this.gates = {
        playbackActive: foreground,
        allowFullscreen: true,
        audioActive: true,
        audioPaused: !foreground
      };
      note('route', 'gate', this.gates);
    },
    observe(session: MediaPlaybackSession) {
      const attach = session.attach.bind(session);
      session.attach = (player, id, kind, callbacks) => {
        if (!live.has(player)) {
          // Observe the native object in place. Every method/event still reaches expo-video.
          const record: Record = {
            player,
            kind,
            serial: ++counts.created,
            timeEvents: 0,
            seeks: 0,
            fullscreen: false,
            fullscreenActive: false,
            detachedAt: null,
            fullscreenExitedAt: null,
            fullscreenExitPosition: null,
            fullscreenExitPlaying: null
          };
          live.set(player, record);
          counts.peakPlayers = Math.max(counts.peakPlayers, live.size);
          player.volume = 0.02;
          const play = player.play.bind(player);
          const pause = player.pause.bind(player);
          player.play = () => {
            note(kind, 'play-call', { serial: record.serial, status: player.status, position: player.currentTime });
            play();
          };
          player.pause = () => {
            note(kind, 'pause-call', { serial: record.serial, status: player.status, position: player.currentTime });
            pause();
          };
          const subscriptions = [
            player.addListener('playingChange', ({ isPlaying }) => note(kind, 'playingChange', isPlaying)),
            player.addListener('playWhenReadyChange', ({ playWhenReady }) =>
              note(kind, 'playWhenReadyChange', playWhenReady)
            ),
            player.addListener('timeUpdate', () => {
              record.timeEvents++;
              changed();
            }),
            player.addListener('positionDiscontinuity', () => {
              record.seeks++;
              changed();
            }),
            player.addListener('statusChange', ({ status, error }) => {
              note(kind, 'statusChange', { status, error });
              if (status === 'error') errors.push(`${kind}: ${error?.message || 'native error'}`);
            }),
            player.addListener('fullscreenChange', ({ fullscreen, active = fullscreen }) => {
              if (fullscreen && !record.fullscreen) counts.fullscreenEntries++;
              if (!fullscreen && record.fullscreen) {
                counts.fullscreenExits++;
                record.fullscreenExitedAt = performance.now();
                record.fullscreenExitPosition = player.currentTime;
                record.fullscreenExitPlaying = player.playing;
              }
              record.fullscreen = fullscreen;
              record.fullscreenActive = fullscreen && active;
              note(kind, 'fullscreenChange', { fullscreen, active });
            })
          ];
          counts.observerSubscriptions += subscriptions.length;
          const release = player.release.bind(player);
          player.release = () => {
            for (const subscription of subscriptions) subscription.remove();
            counts.observerSubscriptions -= subscriptions.length;
            release();
            live.delete(player);
            counts.released++;
            changed();
          };
        }
        const handle = attach(player, id, kind, callbacks);
        const detach = handle.detach.bind(handle);
        handle.detach = (releasePlayer) => {
          detach(releasePlayer);
          const record = live.get(player);
          if (record) {
            record.detachedAt ??= performance.now();
            note(kind, 'handle-detached', record.serial);
          }
        };
        changed();
        return handle;
      };
    }
  };
}
type Observation = ReturnType<typeof observations>;

function Audio({ id, uri, observation }: { id: string; uri: string; observation: Observation }) {
  const admission = useMemo(
    () => ({
      admitted: true,
      attachmentKey: id,
      attemptId: id,
      failure: null,
      progress: () => {},
      retry: () => {},
      settle: (outcome: 'displayed' | 'error') => {
        if (outcome === 'error') observation.errors.push(`${id} admission failed`);
      }
    }),
    [id, observation]
  );
  const control = useTopicAudioControl({ admission, id, mediaContext: context, src: uri });
  useLayoutEffect(() => {
    observation.controls.set(id, control);
    observation.changed();
    return () => {
      if (observation.controls.get(id) === control) observation.controls.delete(id);
      observation.changed();
    };
  }, [control, id, observation]);
  return <ForumContentAudio theme={theme} {...control} />;
}

function Route({
  uris,
  observation,
  audioVisible,
  videoVisible,
  foreground
}: {
  uris: string[];
  observation: Observation;
  audioVisible: boolean;
  videoVisible: boolean;
  foreground: boolean;
}) {
  const [session] = useState(() => {
    const playback = new MediaPlaybackSession();
    observation.observe(playback);
    return playback;
  });
  // Same gate and ownership as TopicBodyMediaCoordinatorSessionProvider.
  useLayoutEffect(() => {
    observation.recordGate(foreground);
    session.updateGate(foreground, true);
  }, [foreground, observation, session]);
  useEffect(() => () => session.dispose(), [session]);
  useEffect(() => {
    observation.recordVideoCommit(videoVisible);
    return () => observation.recordVideoCommit(false);
  }, [observation, videoVisible]);
  return (
    <MediaPlaybackSessionContext.Provider value={session}>
      <TopicAudioSessionProvider
        active
        paused={!foreground}
        runtimeGeneration={getReadNetworkRuntimeSnapshot().generation}
      >
        <Audio id="audio-a" uri={uris[1]!} observation={observation} />
        {audioVisible && <Audio id="audio-b" uri={uris[2]!} observation={observation} />}
        {videoVisible && <ForumContentVideo mediaContext={context} src={uris[0]!} theme={theme} />}
      </TopicAudioSessionProvider>
    </MediaPlaybackSessionContext.Provider>
  );
}

function Proof({ scenario }: { scenario: Scenario }) {
  const [observation] = useState(observations);
  const [uris, setUris] = useState<string[]>([]);
  const [round, setRound] = useState(0);
  const [mounted, setMounted] = useState(false);
  const [audioVisible, setAudioVisible] = useState(true);
  const [videoVisible, setVideoVisible] = useState(true);
  const [foreground, setForeground] = useState(AppState.currentState === 'active');
  const [label, setLabel] = useState('initializing');
  const phase = useRef('initializing');
  const canceled = useRef(false);
  const started = useRef(0);
  const summary = useRef<object[]>([]);
  const backgroundTarget = useRef(0);
  const backgroundSample = useRef<{ serial: number; position: number; at: number; durationMs?: number } | null>(null);
  const snapshot = useCallback(
    () => ({
      gates: observation.gates,
      inlineVideoMounted: observation.inlineVideoMounted,
      controls: [...observation.controls].map(([id, control]) => ({
        id,
        status: control.status,
        playing: control.playing,
        playWhenReady: control.playWhenReady,
        position: control.position,
        duration: control.duration,
        error: control.error
      })),
      livePlayers: observation.live.size,
      players: [...observation.live.values()].map(({ player, ...record }) => ({
        ...record,
        playing: player.playing,
        position: player.currentTime,
        duration: player.duration,
        status: player.status
      })),
      trace: [...observation.trace]
    }),
    [observation]
  );
  const write = useRef((next: string, details: object = {}) => {
    phase.current = next;
    new File(Paths.cache, 'media-pressure-proof.json').write(
      JSON.stringify({
        ...diagnosticBuildContext(),
        ...scenario,
        phase: next,
        elapsedMs: performance.now() - started.current,
        isDev: __DEV__,
        isHermes: 'HermesInternal' in globalThis,
        localMedia: manifest.files,
        generator: manifest.generator,
        appState: AppState.currentState,
        ...observation.counts,
        ...snapshot(),
        completedRounds: summary.current.length,
        roundResults: summary.current,
        errors: observation.errors,
        firstFrameEvidence:
          'notMeasuredByJs: ready/progress is not a displayed-frame oracle; collect native view or screenshot evidence separately',
        releaseEvidence: 'real VideoPlayer.release returned; native decoder and PSS checks belong to the native runner',
        ...details
      })
    );
    setLabel(next);
  });
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (state) => {
      setForeground(state === 'active');
      if (state !== 'active' && phase.current === 'await-background') {
        const record = [...observation.live.values()].find(({ serial }) => serial === backgroundTarget.current);
        if (record)
          backgroundSample.current = {
            serial: record.serial,
            position: record.player.currentTime,
            at: performance.now()
          };
        observation.counts.backgroundEntries++;
        write.current('await-foreground');
      } else if (state === 'active' && phase.current === 'await-foreground') {
        if (backgroundSample.current)
          backgroundSample.current.durationMs = performance.now() - backgroundSample.current.at;
        observation.counts.foregroundReturns++;
        write.current('foreground-observed');
      }
    });
    setForeground(AppState.currentState === 'active');
    return () => subscription.remove();
  }, [observation]);
  useEffect(() => {
    canceled.current = false;
    started.current = performance.now();
    const until = async (description: string, ready: () => boolean, timeout = 20_000) => {
      const deadline = performance.now() + timeout;
      while (!ready()) {
        check(!canceled.current, 'Proof unmounted');
        check(!observation.errors.length, observation.errors.join('; '));
        check(performance.now() < deadline, `Timed out: ${description}`);
        // Fullscreen pauses MainActivity's RN timers. Native events and React commits still wake this wait.
        await waitForMediaProofChange(observation.changes);
      }
    };
    const video = () => [...observation.live.values()].find((record) => record.kind === 'video');
    const audio = () => [...observation.live.values()].find((record) => record.kind === 'audio');
    const control = (id: string) => {
      const value = observation.controls.get(id);
      check(value, `Missing audio control: ${id}`);
      return value;
    };
    const run = async () => {
      await applyNetworkProxy(null);
      const local = await Promise.all(
        assets.map(async (module) => {
          const asset = await Asset.fromModule(module).downloadAsync();
          const uri = asset.localUri;
          check(uri && uri.startsWith('file://'), 'Media must resolve to an app-local file');
          return uri;
        })
      );
      setUris(local);
      await hideAsync();
      for (
        let index = 0;
        index < scenario.rounds || performance.now() - started.current < scenario.minSeconds * 1000;
        index++
      ) {
        const roundStarted = performance.now();
        let fullscreenRetention:
          | {
              serial: number;
              committedAt: number;
              startPosition: number;
              startedPlaying: boolean;
              retainedMs?: number;
              endPosition?: number;
              endedPlaying?: boolean;
            }
          | undefined;
        setRound(index);
        setAudioVisible(true);
        setVideoVisible(true);
        setMounted(true);
        write.current('loading', { round: index });
        await until('audio and video ready', () =>
          Boolean(observation.controls.get('audio-a')?.status === 'ready' && video()?.player.status === 'readyToPlay')
        );
        check(
          control('audio-a').duration > 25 && video()!.player.duration > 25,
          'Native durations must match generated 30-second media'
        );
        check(!video()!.player.playing && !control('audio-a').playing, 'Mount must not autoplay');

        write.current('audio-progress', { round: index });
        observation.note('audio-a', 'control-onPlay');
        control('audio-a').onPlay();
        await until(
          'native audio advances',
          () => control('audio-a').playing && control('audio-a').position >= 0.5 && audio()!.timeEvents > 0
        );
        const initialVideo = video()!;
        initialVideo.player.play();
        await until(
          'video claims playback from audio',
          () => initialVideo.player.playing && !control('audio-a').playing && !control('audio-a').playWhenReady
        );
        const seeks = initialVideo.seeks;
        initialVideo.player.currentTime = 2;
        await until(
          'native video seek and progress',
          () => initialVideo.seeks > seeks && initialVideo.player.currentTime >= 2.5 && initialVideo.timeEvents > 0
        );
        initialVideo.player.pause();
        await until('native video pause', () => !initialVideo.player.playing);
        const pausedPosition = initialVideo.player.currentTime;
        await delay(600);
        check(Math.abs(initialVideo.player.currentTime - pausedPosition) < 0.25, 'Paused video advanced');

        control('audio-b').onPlay();
        await until(
          'second native audio advances',
          () => control('audio-b').playing && control('audio-b').position >= 0.5
        );
        check(
          !control('audio-a').playing && !initialVideo.player.playing,
          'Audio/video playback is not mutually exclusive'
        );
        const audioSeeks = audio()!.seeks;
        control('audio-b').onSeek(3);
        await until('native audio seek', () => audio()!.seeks > audioSeeks && audio()!.player.currentTime >= 3);
        control('audio-b').onPause();
        await until('native audio pause', () => !audio()!.player.playing && !control('audio-b').playWhenReady);
        const audioPosition = control('audio-b').position;
        const audioSerial = audio()!.serial;
        setAudioVisible(false);
        await until('audio row recycled', () => !observation.controls.has('audio-b'));
        setAudioVisible(true);
        await until('audio row restored', () => observation.controls.has('audio-b'));
        check(
          audio()!.serial === audioSerial &&
            Math.abs(control('audio-b').position - audioPosition) < 0.5 &&
            !control('audio-b').playing,
          'Recycled audio lost its owner, position or pause'
        );

        write.current('video-recycle', { round: index });
        setVideoVisible(false);
        await until('recycled video releases native player', () => !observation.live.has(initialVideo.player));
        setVideoVisible(true);
        await until('video remount restores pause and position', () =>
          Boolean(
            video()?.player.status === 'readyToPlay' &&
            Math.abs(video()!.player.currentTime - pausedPosition) < 0.75 &&
            !video()!.player.playing
          )
        );

        if (index % scenario.externalEvery === 0 || index === scenario.rounds - 1) {
          const full = video()!;
          full.player.play();
          await until('video plays before fullscreen', () => full.player.playing);
          write.current('await-fullscreen-enter', { round: index });
          await until('real native fullscreen entered', () => full.fullscreen && full.fullscreenActive, 120_000);
          setVideoVisible(false);
          await until(
            'inline video removal committed during fullscreen',
            () => !observation.inlineVideoMounted && full.detachedAt !== null
          );
          check(
            observation.live.has(full.player) && full.fullscreenActive,
            'Fullscreen player released when inline row recycled'
          );
          await until('native fullscreen plays after inline removal', () => full.player.playing);
          fullscreenRetention = {
            serial: full.serial,
            committedAt: performance.now(),
            startPosition: full.player.currentTime,
            startedPlaying: full.player.playing
          };
          write.current('await-fullscreen-exit', { round: index, fullscreenRetention });
          await until(
            'real native fullscreen exited and detached player released',
            () => !observation.live.has(full.player),
            120_000
          );
          check(
            observation.counts.fullscreenEntries === observation.counts.fullscreenExits,
            'Fullscreen exit event missing'
          );
          fullscreenRetention.retainedMs = (full.fullscreenExitedAt || 0) - fullscreenRetention.committedAt;
          fullscreenRetention.endPosition = full.fullscreenExitPosition ?? undefined;
          fullscreenRetention.endedPlaying = full.fullscreenExitPlaying ?? undefined;
          check(
            fullscreenRetention.retainedMs >= 600,
            'Fullscreen exited before the committed inline removal stayed retained for 600ms'
          );
          check(
            fullscreenRetention.startedPlaying &&
              typeof fullscreenRetention.endPosition === 'number' &&
              fullscreenRetention.endPosition - fullscreenRetention.startPosition >= 0.3,
            'Retained fullscreen did not advance the real native playback position'
          );
          write.current('fullscreen-exited', { round: index, fullscreenRetention });
          setVideoVisible(true);
          await until('inline video returned', () => Boolean(video()?.player.status === 'readyToPlay'));
          const backgroundKind = Math.floor(index / scenario.externalEvery) % 2 === 0 ? 'video' : 'audio';
          const background = backgroundKind === 'video' ? video()! : audio()!;
          background.player.currentTime = 8;
          if (backgroundKind === 'video') background.player.play();
          else control('audio-b').onPlay();
          await until(
            'native player advances before real background',
            () => background.player.playing && background.player.currentTime >= 8.3
          );
          backgroundSample.current = null;
          backgroundTarget.current = background.serial;
          const returns = observation.counts.foregroundReturns;
          write.current('await-background', { round: index, backgroundKind });
          await until(
            'real background and foreground cycle',
            () => observation.counts.foregroundReturns > returns,
            120_000
          );
          await until('returned player remains paused', () => !background.player.playing);
          const returnedPosition = background.player.currentTime;
          const sample = backgroundSample.current as { serial: number; position: number; durationMs?: number } | null;
          check(
            sample?.serial === background.serial && (sample.durationMs || 0) >= 2_000,
            'Runner must hold the real background for at least two seconds'
          );
          check(Math.abs(returnedPosition - sample.position) < 0.75, 'Background changed the saved playback position');
          await delay(1_200);
          check(
            !background.player.playing && Math.abs(background.player.currentTime - returnedPosition) < 0.25,
            'Foreground return autoplayed'
          );
        }

        setMounted(false);
        await until(
          'route releases all native players and observers',
          () =>
            observation.live.size === 0 &&
            observation.controls.size === 0 &&
            observation.counts.observerSubscriptions === 0
        );
        check(observation.counts.created === observation.counts.released, 'Native player release imbalance');
        check(observation.counts.peakPlayers <= 2, 'The fixture owns one video and one shared audio player');
        summary.current.push({
          index,
          elapsedMs: performance.now() - roundStarted,
          created: observation.counts.created,
          released: observation.counts.released,
          ...(fullscreenRetention ? { fullscreenRetention } : {})
        });
        write.current('round-complete', { round: index });
      }
      check(!observation.errors.length, observation.errors.join('; '));
      write.current('passed');
    };
    void run().catch(async (cause: unknown) => {
      const failureState = snapshot();
      const error = cause instanceof Error ? cause.message : String(cause);
      if (!canceled.current) write.current('failed', { error, failureState });
      setMounted(false);
      await delay(500);
      if (!canceled.current) write.current('failed', { error, failureState });
    });
    return () => {
      canceled.current = true;
      observation.changed();
    };
  }, [observation, scenario, snapshot]);
  return (
    <View
      collapsable={false}
      testID="media-pressure-proof"
      style={{ flex: 1, backgroundColor: theme.background, padding: 12, paddingTop: 36 }}
    >
      <Text testID="media-pressure-phase" accessibilityLabel={`media-pressure:${label}`} style={{ color: theme.ink }}>
        {label} / round {round + 1}
      </Text>
      {mounted && uris.length === 3 && (
        <Route
          key={round}
          uris={uris}
          observation={observation}
          audioVisible={audioVisible}
          videoVisible={videoVisible}
          foreground={foreground}
        />
      )}
    </View>
  );
}

function Root() {
  const [scenario, setScenario] = useState<Scenario | null>(null);
  useEffect(() => {
    const accept = (url: string | null) => {
      if (!url) return;
      let parsed: URL;
      try {
        parsed = new URL(url);
      } catch {
        return;
      }
      if (parsed.protocol !== 'wzmediapressure:') return;
      const token = parsed.searchParams.get('token') || '';
      if (!/^[a-zA-Z0-9_-]{8,80}$/.test(token)) return;
      const integer = (name: string, fallback: number, min: number, max: number) => {
        const value = Number(parsed.searchParams.get(name) || fallback);
        return Number.isInteger(value) ? Math.min(max, Math.max(min, value)) : fallback;
      };
      setScenario((previous) =>
        previous?.token === token
          ? previous
          : {
              token,
              rounds: integer('rounds', 20, 20, 100),
              minSeconds: integer('minSeconds', 180, 180, 1800),
              externalEvery: integer('externalEvery', 5, 1, 20)
            }
      );
    };
    void Linking.getInitialURL().then(accept);
    const subscription = Linking.addEventListener('url', ({ url }) => accept(url));
    return () => subscription.remove();
  }, []);
  return scenario ? (
    <Proof key={scenario.token} scenario={scenario} />
  ) : (
    <Text testID="media-pressure-idle">Waiting for isolated media proof URL</Text>
  );
}

registerRootComponent(Root);
