allprojects { project ->
    project.plugins.withId("com.android.application") {
        project.android {
            splits {
                abi {
                    enable true
                    reset()
                    include "armeabi-v7a", "arm64-v8a"
                    universalApk false
                }
            }
        }
    }
}
